# Generated by Django 3.1.7 on 2021-03-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledatafile',
            name='file',
            field=models.FileField(blank=True, upload_to='datafiles/'),
        ),
    ]
