# Generated by Django 3.1.7 on 2021-03-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210322_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledatafile',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
