# Generated by Django 3.1.7 on 2021-03-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210322_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=151)),
                ('file_name', models.CharField(max_length=200)),
                ('original_file_name', models.CharField(max_length=200)),
            ],
        ),
    ]
