# Generated by Django 3.1.7 on 2021-03-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartDataFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_chart', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
