# Generated by Django 3.1.7 on 2021-03-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_chartdatafile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartdatafile',
            old_name='file_chart',
            new_name='chart_file',
        ),
    ]
