# Generated by Django 3.1.7 on 2021-03-29 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210328_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartdatafile',
            old_name='chart_file',
            new_name='chartfile',
        ),
    ]
